[build]
builder = "nixpacks"
buildCommand = "chmod +x ./build-app.sh && ./build-app.sh"

[deploy]
startCommand = "chmod +x ./start.sh && ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "web"
protocol = "tcp"
port = "80"

[services.environment]
PHP_CLI_SERVER_WORKERS = "4"
